name: Deploy Site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages-deployment"
  cancel-in-progress: false

jobs:
  deploy_static_site:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Source Code
        uses: actions/checkout@v4

      - name: Configure GitHub Pages Environment
        uses: actions/configure-pages@v5

      - name: Prepare Static Site Assets
        run: |
          # Define the output directory
          output_dir="public"
          mkdir -p $output_dir
          # Copy primary HTML file and any associated assets to the output directory
          cp index.html $output_dir/
          cp -r static $output_dir/

      - name: Package Deployment Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
